# Generated by Django 4.1.3 on 2022-12-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_portal", "0002_job_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="sellery",
            field=models.CharField(max_length=30),
        ),
    ]
