# Generated by Django 4.1.3 on 2022-12-01 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_date_joined_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entred in the format: +8801555555550, Up to 11 digits allowed.",
                        regex="^(((?:\\+88)?(?:\\d{11}))|((?:01)?(?:\\d{11})))$",
                    )
                ],
            ),
        ),
    ]
